### ISSUE TITLE
Add textual instructions or help

### ISSUE THREAD

**Issue by roryokane** [electronicwhisper/recursive-drawing#4]
When this app was [submitted to Hacker News](https://news.ycombinator.com/item?id=3951255), I wrote [a comment with textual instructions](https://news.ycombinator.com/item?id=3951499). This comment was the top-voted, with 27 points, which indicates that many people want textual instructions.

The app should show instructions somewhere. An easy place to add them is [the home page](http://recursivedrawing.com/), though that leaves users unable to reference the instructions while they use the app. But it’s better to put them on the home page than nowhere at all because it’s too hard to add them anywhere else. You are free to use my instructions, verbatim or edited:

> Textual instructions (if you don't want to watch the demo video):
> 
> The left column is the shapes library. The center area is the canvas/workspace. The right area is an outline view of the shapes in the canvas.
> 
> To add a shape to the canvas, drag your mouse from the shape in the shape library to the workspace.
> 
> To move a shape, drag inside it, when the whole shape is highlighted red.
> 
> To resize and rotate a shape, drag the edge of it, when it is outlined red.
> 
> To delete a shape on the canvas, right-click it and choose Delete Shape. (You currently cannot delete shapes directly from the outline, nor can you delete shapes from the shape library.)
> 
> To resize a shape non-uniformly or add skew, hold shift while dragging its outline. You can use this to make line segments and rhombuses, among other things.
> 
> Click the + button in the left column to start editing a new shape.
> 
> Remember that you can add any shape to the canvas by dragging it from the shape library. This also applies to shapes you create yourself.
> 
> Click on any shape in the shape library (except for the starting circle and square) to edit it in the canvas.
> 
> You can see the thumbnail of what's in the canvas in the current shape in the shape library. You can also see the shapes your shape is composed of in the outline. Everything is updated live.
> 
> To pan across the canvas, drag outside of any shape, in the white area. To zoom into or out from the canvas, scroll with the mouse wheel while pointing inside the canvas.
> 
> You can drag even the shape you are currently editing from the shape library into the canvas. That is what makes this recursive drawing rather than merely nested drawing. You will see the current shape repeated relative to itself. (You might call the shape inside itself a "recursive shape instance".)
> 
> You can move, rotate, and resize a recursive shape instance to change its repetition pattern. For instance, if you resize the recursive shape instance to be smaller, you will see a line of recursive shapes shrinking forever. If you edit one of the repetitions of a shape, it will edit the whole pattern.
> 
> You can go back and edit a sub-shape, and every shape including that shape will update live.
> 
> If you don't know what to draw, try drawing one of these: any kind of fractal tree (https://www.google.com/search?q=fractal+tree&tbm=isch&biw=1280&bih=1252), Koch snowflake (http://en.wikipedia.org/wiki/Koch_snowflake), Sierpinski triangle (http://en.wikipedia.org/wiki/Sierpinski_triangle), Sierpinski carpet (http://en.wikipedia.org/wiki/Sierpinski_carpet), or any other fractal (http://en.wikipedia.org/wiki/List_of_fractals).

In my instructions, I made each step build on the previous ones, like a tutorial, and I also covered all features of the app, like a reference. Since my instructions are a compromise between a tutorial and a reference, if you want a tutorial and a reference separately, my instructions should be adapted for each format. An interactive tutorial (shown in a floating window with a Next button) could show one paragraph per step, but it might leave some less-useful steps out so as not to bore the reader, and link to the full reference at the end. A reference might be written as bullet points instead of sentences, and have the features organized in sections – perhaps a section briefly describing the three columnar views and then one section per view describing the actions you can do in each.

The last paragraph of my instructions is a bit different from the others – it suggests tasks to give the user something to do and spark their imagination, instead of explaining a specific feature of the app – so it’s possible that you’d want to move it somewhere else.

**Comment by electronicwhisper** [comment]
Hi Rory,

Thanks for writing these instructions. I think you're right that they were really helpful when Recursive Drawing hit HN.

In lieu of something fancier, I'm putting a link to your original instructions on the homepage.

Toby

**Comment by roryokane** [comment]
Thanks for the link and credit, Toby.

---

For future reference, the link to my instructions was added in this commit: a93cc63d16e5bda3f3a3d8b625d14436c08cca61
